export interface AIAssistant {
  docNo?: string; 
  poNo?: string; 
  reqNo?: string | null;
  revisionNo?: string | null;
  poDate?: string | null;
  suppName?: string | null;
  jobName?: string | null;
  poExpenseType?: string | null;
  lcy?: number | null;
  poAmount?: number | null;
  currencyCode?: string | null;
  flag?: string | null;
  forwardedDate?: string | null;
  forwardedFrom?: string | null;
  generatedBy?: string | null;
  onWhoseDesk?: string | null;
  status?: string | null;
  remarks?: string | null;
}

// AI Assistant Types
export interface AIProvider {
  url: string;
  apiKey: string;
}

export interface AIModel {
  model: string;
  temperature?: number;
}

export interface Subdivision {
  subdivisionName: string;
  subdivisionValue: string;
}

export interface AIDivision {
  divisionName: string;
  divisionValue: string;
  subdivisions?: Subdivision[];
}

export interface AIField {
  division: string;
  tName: string; // Table Name
  fName: string; // Field Name
  fDatatype: string; // Field Datatype
  fieldDesc: string; // Field Description
}

export type AIMode = 'General' | 'Read Image/PDF' | 'SQL Assistant';

export interface ConversationMessage {
  role: 'user' | 'assistant';
  content: string;
  timestamp?: Date;
}

export interface SQLQueryResult {
  columns: string[];
  rows: Record<string, any>[];
}

// Paginated SQL query result
export interface PaginatedSQLQueryResult {
  data: SQLQueryResult;
  success: boolean;
  message?: string;
  pagination: {
    page: number;
    limit: number;
    total: number;
    totalPages: number;
  };
}

export interface SchemaSnapshot {
  database: string;
  tables: Record<string, TableSchema>;
}

export interface TableSchema {
  qualifiedName?: string;
  columns: Record<string, ColumnInfo>;
}

export interface ColumnInfo {
  type: string;
  description: string;
}

export interface AISystemPrompt {
  systemPrompt: string;
  generalPrompt?: string;
}

export interface ChatMessage {
  role: 'system' | 'user' | 'assistant';
  content: string | Array<{
    type: 'text' | 'image_url';
    text?: string;
    image_url?: { url: string };
  }>;
}

export interface ChatResponse {
  choices: Array<{
    message: {
      role: string;
      content: string;
    };
  }>;
  usage?: {
    prompt_tokens?: number;
    completion_tokens?: number;
    total_tokens?: number;
  };
}

export interface SQLGenerationRequest {
  sql: string;
  notes?: string;
  usage?: {
    prompt_tokens?: number;
    completion_tokens?: number;
    total_tokens?: number;
  };
}

// AI Message Log for database storage
export interface AIMessageLog {
  messageId?: string; // GUID - Auto-generated by backend if empty
  conversationId: string; // GUID - Required
  turnIndex?: number;
  role: string; // 'user' | 'assistant' | 'system' - Required
  content: string; // Required
  createdUtc?: string; // ISO 8601 format - Auto-set if not provided
  model?: string;
  temperature?: number;
  latencyMs?: number;
  tokensPrompt?: number;
  tokensCompletion?: number;
  tokensTotal?: number;
  taskType?: string; // 'SQL Assistant' | 'General Assistant' | 'Read Image/PDF'
  appUserHash?: string; // Set by backend from authenticated user
  orgId?: string;
  toolCallsJson?: string;
  responseOk?: boolean;
  errorType?: string;
  derivedJson?: string;
}

